### PR TITLE
Add scripts to run test plugins from inside neovim

### PR DESCRIPTION
**Pull request by saep**
They are used by the test in test suite file
`test-suite/Neovim/RunNeovimWithTestPluginsSpec.hs`
and commented.

### CODE REVIEW

**Comment by saep** [comment]
Since the test is executing a shell script, this will not work on windows, though.

**Comment by osa1** [comment]
I'm now a Windows pro but I think there are some bash implementations for Windows too.. It should be OK I think.

**Comment by saep** [comment]
I've been trying some ways to integrate this inside the test suite without affecting the actual binary, but I could not find a reliable and generic way to do so. I think that the best we can do is to create a sub-project that also serves as an example plugin.

**Comment by osa1** [comment]
What do you mean by "affecting the actual binary"? I think your approach looks fine. Maybe we can change it slightly to do something like this:

1. Test program checks if we have ./.cabal-sandbox in the current directory.
2. Makes sure we have `nvim-hs` in `cabal sandbox hc-pkg list` output.
3. We have a directory where every subdirectory of it has a .hs file and a .vim file.
4. Test runner compiles .hs file with `cabal exec ghc --make -outputdir <some temp file created in pwd>`
5. Test runner runs `nvim --headless -S <test script>`, gives it 10 seconds at most, and checks the return value.

**Comment by saep** [comment]
Oh, I wanted the tests to run on Travis. I tried a couple of different approaches which all failed to run even locally. 

* runhaskell or runghc do not seem to be on PATH on Travis, so the plugin provider script does not work. So I tried to accomplish the task using cabal run which led to the next difficulties.
* Adding a command line option to change the path to the .hs files that dye compiles causes a weird early exit even though invoking the compiled binary directly works. 


So I assumed that it can only be run reliably if the plugins were hard-coded into the binary.

**Comment by osa1** [comment]
> runhaskell or runghc do not seem to be on PATH on Travis, so the plugin provider script does not work. So I tried to accomplish the task using cabal run which led to the next difficulties.

We're installing GHC using this ppa: https://launchpad.net/~hvr/+archive/ubuntu/ghc/+packages I'm not sure where are executables installed and I don't know if it's possible to look contents of .deb files to see what it's going to do.

**Comment by saep** [comment]
The problem was not to use `cabal install` in the travis script since the test needed the nvim-hs library to be installed due to using runghc.

**Pull request merged**
