### PR TITLE
Remove the `ExceptT` stack from the `Neovim` type

### PR DESCRIPTION
**Pull request by saep**
This should adress the following issues:
* Needless exception stack as IO already supports exceptions
* Since runNeovim now catches all exceptions, the plugin provider should not
  crash anymore (and possibly cause neovim to hang)

### CODE REVIEW

**Comment by osa1** [comment]
Looks good :+1:

**Comment by saep** [comment]
Do your test plugins still work with this?

**Comment by saep** [comment]
Note that we do not handle stateful functions here. If an exception is thrown within such a function, the event loop is not going to read a request anymore and neovim will likely start to hang again. We have to restart the function's "loop" or unregister all affected functions from the event handler.

**Comment by osa1** [comment]
> Do your test plugins still work with this?

It works, but since we lost `MonadError String` instance with this patch I need to throw an `IOException`.

> Note that we do not handle stateful functions here. If an exception is thrown within such a function, the event loop is not going to read a request anymore and neovim will likely start to hang again. We have to restart the function's "loop" or unregister all affected functions from the event handler.

Yeah, we should send an error response when that happens to prevent vim from hanging.

**Pull request merged**
